[build]
base = "/"
command = "npm run build"
publish = "build/"

[[redirects]]
from = "/*"
status = 200
to = "/index.html"

[[headers]]
for = "/static/*"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "/routes/*"
[headers.values]
Cache-Control = "public, max-age=3600"

[[headers]]
for = "/segments/*"
[headers.values]
Cache-Control = "public, max-age=3600"
