runtime: nodejs16

instance_class: F1

inbound_services:
  - warmup

automatic_scaling:
  max_instances: 1

env_variables:
  BACKEND_URL: https://api2.zwiftmap.com
  FRONTEND_URL: https://zwiftmap.com

  STRAVA_CLIENT_ID: 66426

  PORT: 8080

  FUNCTIONS_BASE_URL: https://europe-west1-zwift-map.cloudfunctions.net
  TASKS_LOCATION: europe-west1
  SERVICE_ACCOUNT: zwift-map@appspot.gserviceaccount.com
