name: Build & Deploy

on:
  - push

jobs:
  frontend:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Switch node version
        shell: bash -l {0}
        run: nvm install

      - name: Install
        run: npm install --no-optional
        working-directory: frontend
      - name: Test
        run: npm test
        working-directory: frontend
      - name: Build
        run: npm run build
        working-directory: frontend

      - name: Deploy
        run: |
          if [[ ${{ github.ref }} == "refs/heads/main" ]]; then
            npm run deploy -- --prod
          else
            npm run deploy
          fi
        working-directory: frontend
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

  backend:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Switch node version
        shell: bash -l {0}
        run: nvm install

      - name: Install
        run: npm ci
        working-directory: backend
      - name: Build
        run: npm run build
        working-directory: backend

  static-map:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Switch node version
        shell: bash -l {0}
        run: nvm install

      - name: Install
        run: npm ci
        working-directory: static-map
      - name: Build
        run: npm run build
        working-directory: static-map

      - name: Deploy
        run: |
          if [[ ${{ github.ref }} == "refs/heads/main" ]]; then
            npm run deploy -- --prod
          else
            npm run deploy
          fi
        working-directory: frontend
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_STATIC_SITE_ID }}